name: auto-release
on:
  push:
    brances:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: release vault-operator to docker registry
        run: make -f vault-operator/Makefile release
